
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { resolve } from "path";
import { defineConfig, env } from "prisma/config";

// Charger le .env depuis la racine du projet
config({ path: resolve(__dirname, "../.env") });

// Récupérer DATABASE_URL et remplacer 'db' par 'localhost' seulement hors Docker
let databaseUrl = env("DATABASE_URL");
const inDocker =
  env("DOCKER") === "true" ||
  env("IN_DOCKER") === "true" ||
  process.env.CONTAINER === "true";
if (!inDocker && databaseUrl && databaseUrl.includes("@db:")) {
  databaseUrl = databaseUrl.replace("@db:", "@localhost:");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: databaseUrl,
  },
});
